// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    jQuery(function() {
      return $(".ambilight-table").ambilight();
    });
    return $(document).on("keydown", function(e) {
      if ([37, 38, 39, 40].indexOf(e.keyCode) > -1) {
        return $("#instructions").fadeOut();
      }
    });
  });

}).call(this);
